name: password_protector
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    
    sdk: flutter


  cupertino_icons: ^1.0.2
  local_auth: ^2.1.2
  flutter_pin_code_widget: ^0.0.4+2
  passwordfield: ^0.1.0
  settings_ui: ^2.0.2
  flutter_keychain: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:
  uses-material-design: true

