name: password_protector
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    
    sdk: flutter


  cupertino_icons: ^1.0.2
  local_auth: ^2.1.2
  flutter_pin_code_widget: ^0.0.4+2
  passwordfield: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

